site_name: Web3-wiki

nav:
- 首页: "index.md"
- "基本区块链知识":
  - "什么是区块链":
    - "正文": "基本区块链知识/什么是区块链.md"
    - "相关网页中文翻译":
      - "区块链定义解释": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链定义解释.md"
      - "什么是去中心化？": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是去中心化？.md"
      - "区块链是如何运作的？": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链是如何运作的？.md"
      - "什么是区块链？ | 开发人员的区块链基础知识": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是区块链-开发人员的区块链基础知识.md"
  - "权力下放": 
    - "正文": "基本区块链知识/权力下放.md"
    - "相关网页中文翻译":
      - "什么是权力下放？": "基本区块链知识/中文网页/权力下放-中文网页/什么是权力下放？.md"
      - "在区块链中，权力下放的作用是什么？": "基本区块链知识/中文网页/权力下放-中文网页/在区块链中，权力下放的作用是什么？.md"
  - "为什么区块链重要":
    - "正文": "基本区块链知识/为什么区块链重要.md"
    - "相关网页中文翻译":
      - "为什么是区块链？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么是区块链？.md"
      - "什么是区块链，为什么它很重要？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/什么是区块链，为什么它很重要？.md"
      - "Web3/密码:为什么要兼得？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/Web3&密码为什么要兼得？.md"
      - "为什么区块链很重要以及为什么它很重要": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么区块链很重要以及为什么它很重要.md"
  - "区块链结构":
    - "正文": "基本区块链知识/区块链结构.md"
    - "相关网页中文翻译":
      - "区块链架构基础：组件、结构、收益和创造": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构基础：组件、结构、收益和创造.md"
      - "区块链架构 101：组件、结构和优势": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构 101：组件、结构和优势.md"
      - "区块链结构": "基本区块链知识/中文网页/区块链结构-中文网页/区块链结构.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/区块链结构-中文网页/区块链基础｜Coursera.md"
  - "基本区块链操作":
    - "正文": "基本区块链知识/基本区块链操作.md"
    - "相关网页中文翻译":
      - "区块链基础知识：结构、操作和比特币区块链": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础知识：结构、操作和比特币区块链.md"
      - "比特币区块链交易 | 比特币开发者": "基本区块链知识/中文网页/基本区块链操作-中文网页/比特币区块链交易--比特币开发者.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/基本区块链操作-中文网页/以太坊区块链交易--ethereum.org.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础--Coursera.md"
  - "区块链技术的应用和用途":
    - "正文": "基本区块链知识/区块链技术的应用和用途.md"
    - "相关网页中文翻译":
      - "区块链技术的应用和用途": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的应用和用途.md"
      - "区块链技术的十大现实应用": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的十大现实应用.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/以太坊区块链交易--ethereum.org.md"
      - "打破现状的区块链应用和现实世界用例 E34": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/打破现状的区块链应用和现实世界用例 E34.md"
- "区块链常识":
  - "贮存":
    - "正文": "区块链常识/贮存.md"
    - "相关网页中文翻译":
      - "区块链贮存": "区块链常识/中文网页/贮存-中文页面/区块链贮存.md"
      - "去中心化存储": "区块链常识/中文网页/贮存-中文页面/去中心化存储.md"
      - "IPFS的工作原理": "区块链常识/中文网页/贮存-中文页面/IPFS的工作原理.md"
  - "挖矿和激励模型":
    - "正文": "区块链常识/挖矿和激励模型.md"
    - "相关网页中文翻译":
      - "区块链对矿工的激励": "区块链常识/中文网页/挖矿和激励模型-中文页面/区块链对矿工的激励.md"
      - "以太坊共识机制": "区块链常识/中文网页/挖矿和激励模型-中文页面/以太坊共识机制.md"
      - "Solana 质押奖励": "区块链常识/中文网页/挖矿和激励模型-中文页面/Solana 质押奖励.md"
  - "权力下放与信任":
    - "正文": "区块链常识/权力下放与信任.md"
    - "相关网页中文翻译":
      - "加密货币到底是什么": "区块链常识/中文网页/权力下放与信任-中文页面/加密货币到底是什么.md"
      - "以太坊共识机制": "区块链常识/中文网页/权力下放与信任-中文页面/以太坊共识机制.md"
      - "密码真理的优越性": "区块链常识/中文网页/权力下放与信任-中文页面/密码真理的优越性.md"
  - "区块链分叉":
    - "正文": "区块链常识/区块链分叉.md"
    - "相关网页中文翻译":
      - "区块链分叉": "区块链常识/中文网页/区块链分叉-中文页面/区块链分叉.md"
      - "什么是分叉？": "区块链常识/中文网页/区块链分叉-中文页面/什么是分叉？.md"
      - "什么是硬分叉？": "区块链常识/中文网页/区块链分叉-中文页面/什么是硬分叉？.md"
  - "加密货币":
    - "正文": "区块链常识/加密货币.md"
    - "相关网页中文翻译":
      - "什么是加密货币？": "区块链常识/中文网页/加密货币-中文页面/什么是加密货币？.md"
      - "加密货币是什么以及是怎样运作的？": "区块链常识/中文网页/加密货币-中文页面/加密货币是什么以及是怎样运作的？.md"
      - "加密货币的实际运作方式": "区块链常识/中文网页/加密货币-中文页面/加密货币的实际运作方式.md"
  - "加密钱包":
    - "正文": "区块链常识/加密钱包.md"
    - "相关网页中文翻译":
      - "什么是区块链钱包？": "区块链常识/中文网页/加密钱包-中文页面/什么是区块链钱包？.md"
      - "什么是加密钱包？ 初学者指南": "区块链常识/中文网页/加密钱包-中文页面/什么是加密钱包？ 初学者指南.md"
  - "密码学":
    - "正文": "区块链常识/密码学.md"
    - "相关网页中文翻译":
      - "密码学": "区块链常识/中文网页/密码学-中文页面/密码学.md"
      - "什么是密码学？": "区块链常识/中文网页/密码学-中文页面/什么是密码学？.md"
      - "非对称加密 - 简单解释": "区块链常识/中文网页/密码学-中文页面/非对称加密 - 简单解释.md"
      - "学习密码学": "区块链常识/中文网页/密码学-中文页面/学习密码学.md"
  - "共识协议":
    - "正文": "区块链常识/共识协议.md"
    - "相关网页中文翻译":
      - "区块链中的共识机制：初学者指南": "区块链常识/中文网页/共识协议-中文页面/区块链中的共识机制：初学者指南.md"
      - "共识机制": "区块链常识/中文网页/共识协议-中文页面/共识机制.md"
      - "什么是共识机制？": "区块链常识/中文网页/共识协议-中文页面/什么是共识机制？.md"
  - "区块链互操作性":
    - "正文": "区块链常识/区块链互操作性.md"
    - "相关网页中文翻译":
      - "跨链互操作性：对区块链意味着什么": "区块链常识/中文网页/区块链互操作性-中文页面/跨链互操作性：对区块链意味着什么.md"
      - "区块链互操作性：为什么跨链技术很重要？": "区块链常识/中文网页/区块链互操作性-中文页面/区块链互操作性：为什么跨链技术很重要？.md"
      - "区块链互操作性——了解跨链技术": "区块链常识/中文网页/区块链互操作性-中文页面/区块链互操作性——了解跨链技术.md"
  - "区块链":
    - "正文": "区块链常识/区块链.md"
    - "相关网页中文翻译":
      - "正文开头":
        - "区块链的类型：PoW、PoS 和私有": "区块链常识/中文网页/区块链-中文页面/正文开头/区块链的类型：PoW、PoS 和私有.md"
        - "区块链的类型": "区块链常识/中文网页/区块链-中文页面/正文开头/区块链的类型.md"
      - "Solana":
        - "什么是 Solana，它是如何工作的？": "区块链常识/中文网页/区块链-中文页面/Solana/什么是 Solana，它是如何工作的？.md"
        - "Solana 初学者指南": "区块链常识/中文网页/区块链-中文页面/Solana/Solana 初学者指南.md"
        - "Solana简介": "区块链常识/中文网页/区块链-中文页面/Solana/Solana简介.md"
        - "Solana架构": "区块链常识/中文网页/区块链-中文页面/Solana/Solana架构.md"
        - "开始构建 Solana！": "区块链常识/中文网页/区块链-中文页面/Solana/开始构建 Solana！.md"
      - "TON":
        - "TON Telegram 集成突出了区块链社区的协同作用": "区块链常识/中文网页/区块链-中文页面/TON/TON Telegram 集成突出了区块链社区的协同作用.md"
        - "开始在开放网络上构建": "区块链常识/中文网页/区块链-中文页面/TON/开始在开放网络上构建.md"
        - "TON简介": "区块链常识/中文网页/区块链-中文页面/TON/TON简介.md"
        - "区块链分析": "区块链常识/中文网页/区块链-中文页面/TON/区块链分析.md"
      - "基于EVM":
        - "什么是以太坊虚拟机？": "区块链常识/中文网页/区块链-中文页面/基于EVM/什么是以太坊虚拟机？.md"
        - "基于EVM的区块链":
          - "以太坊":
            - "以太坊白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/以太坊/以太坊白皮书.md"
            - "以太坊介绍": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/以太坊/以太坊介绍.md"
            - "以太坊简介": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/以太坊/以太坊简介.md"
          - "Polygon":
            - "Polygon白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Polygon/Polygon白皮书.md"
            - "介绍Polygon": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Polygon/介绍Polygon.md"
          - "币安智能链":
            - "币安白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/币安智能链/币安白皮书.md"
            - "BNB链概述": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/币安智能链/BNB链概述.md"
          - "灵知链":
            - "Gnosis白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/灵知链/Gnosis白皮书.md"
            - "Gnosis 概述": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/灵知链/Gnosis 概述.md"
          - "火币生态链":
            - "火币生态链白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/火币生态链/火币生态链白皮书.md"
            - "HECO链介绍": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/火币生态链/HECO链介绍.md"
          - "Avalanche":
            - "Avalanche 白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Avalanche/Avalanche 白皮书.md"
            - "官网": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Avalanche/官网.md"
          - "Fantom":
            - "Fantom白皮书": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Fantom/Fantom白皮书.md"
            - "Fantom概览": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Fantom/Fantom概览.md"
          - "Moonbeam/Moonriver":
            - "关于Moonbream": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Moonbeam&Moonriver/关于Moonbream.md"
            - "Moonbeam概览": "区块链常识/中文网页/区块链-中文页面/基于EVM/基于EVM的区块链/Moonbeam&Moonriver/Moonbeam概览.md"
      - "L2区块链":
        - "Layer-1 和 Layer-2 区块链扩展解决方案": "区块链常识/中文网页/区块链-中文页面/L2区块链/Layer-1 和 Layer-2 区块链扩展解决方案.md"
        - "Layer- 2 币安学院": "区块链常识/中文网页/区块链-中文页面/L2区块链/Layer- 2 币安学院.md"
        - "L2区块链包括":
          - "Arbitrum":
            - "Arbitrum白皮书": "区块链常识/中文网页/区块链-中文页面/L2区块链/L2区块链包括/Arbitrum/Arbitrum白皮书.md"
            - "Arbitrum内核": "区块链常识/中文网页/区块链-中文页面/L2区块链/L2区块链包括/Arbitrum/Arbitrum内核.md"

theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette:  # 颜色
    primary: 'default'
    accent: 'indigo'
  feature:
    tabs: false  # 横向导航