site_name: Web3-wiki

nav:
- 首页: "index.md"
- "基本区块链知识":
  - "什么是区块链":
    - "正文": "基本区块链知识/什么是区块链.md"
    - "相关网页中文翻译":
      - "区块链定义解释": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链定义解释.md"
      - "什么是去中心化？": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是去中心化？.md"
      - "区块链是如何运作的？": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链是如何运作的？.md"
      - "什么是区块链？ | 开发人员的区块链基础知识": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是区块链-开发人员的区块链基础知识.md"
  - "权力下放": 
    - "正文": "基本区块链知识/权力下放.md"
    - "相关网页中文翻译":
      - "什么是权力下放？": "基本区块链知识/中文网页/权力下放-中文网页/什么是权力下放？.md"
      - "在区块链中，权力下放的作用是什么？": "基本区块链知识/中文网页/权力下放-中文网页/在区块链中，权力下放的作用是什么？.md"
  - "为什么区块链重要":
    - "正文": "基本区块链知识/为什么区块链重要.md"
    - "相关网页中文翻译":
      - "为什么是区块链？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么是区块链？.md"
      - "什么是区块链，为什么它很重要？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/什么是区块链，为什么它很重要？.md"
      - "Web3/密码:为什么要兼得？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/Web3&密码为什么要兼得？.md"
      - "为什么区块链很重要以及为什么它很重要": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么区块链很重要以及为什么它很重要.md"
  - "区块链结构":
    - "正文": "基本区块链知识/区块链结构.md"
    - "相关网页中文翻译":
      - "区块链架构基础：组件、结构、收益和创造": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构基础：组件、结构、收益和创造.md"
      - "区块链架构 101：组件、结构和优势": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构 101：组件、结构和优势.md"
      - "区块链结构": "基本区块链知识/中文网页/区块链结构-中文网页/区块链结构.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/区块链结构-中文网页/区块链基础｜Coursera.md"
  - "基本区块链操作":
    - "正文": "基本区块链知识/基本区块链操作.md"
    - "相关网页中文翻译":
      - "区块链基础知识：结构、操作和比特币区块链": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础知识：结构、操作和比特币区块链.md"
      - "比特币区块链交易 | 比特币开发者": "基本区块链知识/中文网页/基本区块链操作-中文网页/比特币区块链交易--比特币开发者.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/基本区块链操作-中文网页/以太坊区块链交易--ethereum.org.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础--Coursera.md"
  - "区块链技术的应用和用途":
    - "正文": "基本区块链知识/区块链技术的应用和用途.md"
    - "相关网页中文翻译":
      - "区块链技术的应用和用途": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的应用和用途.md"
      - "区块链技术的十大现实应用": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的十大现实应用.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/以太坊区块链交易--ethereum.org.md"
      - "打破现状的区块链应用和现实世界用例 E34": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/打破现状的区块链应用和现实世界用例 E34.md"
- "区块链常识":
  - "贮存":
    - "正文": "区块链常识/贮存.md"
    - "相关网页中文翻译":
      - "区块链贮存": "区块链常识/中文网页/贮存-中文网页/区块链贮存.md"
      - "去中心化存储": "区块链常识/中文网页/贮存-中文网页/去中心化存储-中文网页.md"
      - "IPFS的工作原理": "区块链常识/中文网页/贮存-中文网页/IPFS的工作原理.md"
  - "挖矿和激励模型":
    - "正文": "区块链常识/挖矿和激励模型.md"
    - "相关网页中文翻译":
      - "区块链对矿工的激励": "区块链常识/中文网页/挖矿和激励模型-中文网页/区块链对矿工的激励.md"
      - "以太坊共识机制": "区块链常识/中文网页/挖矿和激励模型-中文网页/以太坊共识机制.md"
      - "Solana 质押奖励": "区块链常识/中文网页/挖矿和激励模型-中文网页/Solana 质押奖励.md"
  - "权力下放与信任":
    - "正文": "区块链常识/权力下放与信任.md"
    - "相关网页中文翻译":
      - "加密货币到底是什么": "区块链常识/中文网页/权力下放与信任-中文网页/加密货币到底是什么.md"
      - "以太坊共识机制": "区块链常识/中文网页/权力下放与信任-中文网页/以太坊共识机制.md"
      - "密码真理的优越性": "区块链常识/中文网页/权力下放与信任-中文网页/密码真理的优越性.md"
  - "区块链分叉":
    - "正文": "区块链常识/区块链分叉.md"
    - "相关网页中文翻译":
      - "区块链分叉": "区块链常识/中文网页/区块链分叉-中文网页/区块链分叉.md"
      - "什么是分叉？": "区块链常识/中文网页/区块链分叉-中文网页/什么是分叉？.md"
      - "什么是硬分叉？": "区块链常识/中文网页/区块链分叉-中文网页/什么是硬分叉？.md"
  - "加密货币":
    - "正文": "区块链常识/加密货币.md"
    - "相关网页中文翻译":
      - "什么是加密货币？": "区块链常识/中文网页/加密货币-中文网页/什么是加密货币？.md"
      - "加密货币是什么以及是怎样运作的？": "区块链常识/中文网页/加密货币-中文网页/加密货币是什么以及是怎样运作的？.md"
      - "加密货币的实际运作方式": "区块链常识/中文网页/加密货币-中文网页/加密货币的实际运作方式.md"
  - "加密钱包":
    - "正文": "区块链常识/加密钱包.md"
    - "相关网页中文翻译":
      - "什么是区块链钱包？": "区块链常识/中文网页/加密钱包-中文网页/什么是区块链钱包？.md"
      - "什么是加密钱包？ 初学者指南": "区块链常识/中文网页/加密钱包-中文网页/什么是加密钱包？ 初学者指南.md"
  - "密码学":
    - "正文": "区块链常识/密码学.md"
    - "相关网页中文翻译":
      - "密码学": "区块链常识/中文网页/密码学-中文网页/密码学.md"
      - "什么是密码学？": "区块链常识/中文网页/密码学-中文网页/什么是密码学？.md"
      - "非对称加密 - 简单解释": "区块链常识/中文网页/密码学-中文网页/非对称加密 - 简单解释.md"
      - "学习密码学": "区块链常识/中文网页/密码学-中文网页/学习密码学.md"
  - "共识协议":
    - "正文": "区块链常识/共识协议.md"
    - "相关网页中文翻译":
      - "区块链中的共识机制：初学者指南": "区块链常识/中文网页/共识协议-中文网页/区块链中的共识机制：初学者指南.md"
      - "共识机制": "区块链常识/中文网页/共识协议-中文网页/共识机制.md"
      - "什么是共识机制？": "区块链常识/中文网页/共识协议-中文网页/什么是共识机制？.md"
  - "区块链互操作性":
    - "正文": "区块链常识/区块链互操作性.md"
    - "相关网页中文翻译":
      - "跨链互操作性：对区块链意味着什么": "区块链常识/中文网页/区块链互操作性-中文网页/跨链互操作性：对区块链意味着什么.md"
      - "区块链互操作性：为什么跨链技术很重要？": "区块链常识/中文网页/区块链互操作性-中文网页/区块链互操作性：为什么跨链技术很重要？.md"
      - "区块链互操作性——了解跨链技术": "区块链常识/中文网页/区块链互操作性-中文网页/区块链互操作性——了解跨链技术.md"
  - "区块链":
    - "正文": "区块链常识/区块链/区块链.md"
    - "Solana": "区块链常识/区块链/Solana.md"
    - "TON": "区块链常识/区块链/TON.md"
    - "基于EVM": "区块链常识/区块链/基于EVM.md"
    - "L2区块链": "区块链常识/区块链/L2区块链.md"
    - "相关网页中文翻译":
      - "正文开头":
        - "区块链的类型：PoW、PoS 和私有": "区块链常识/中文网页/区块链-中文网页/正文开头/区块链的类型：PoW、PoS 和私有.md"
        - "区块链的类型": "区块链常识/中文网页/区块链-中文网页/正文开头/区块链的类型.md"
      - "Solana":
        - "什么是 Solana，它是如何工作的？": "区块链常识/中文网页/区块链-中文网页/Solana/什么是 Solana，它是如何工作的？.md"
        - "Solana 初学者指南": "区块链常识/中文网页/区块链-中文网页/Solana/Solana 初学者指南.md"
        - "Solana简介": "区块链常识/中文网页/区块链-中文网页/Solana/Solana简介.md"
        - "Solana架构": "区块链常识/中文网页/区块链-中文网页/Solana/Solana架构.md"
        - "开始构建 Solana！": "区块链常识/中文网页/区块链-中文网页/Solana/开始构建 Solana！.md"
      - "TON":
        - "TON Telegram 集成突出了区块链社区的协同作用": "区块链常识/中文网页/区块链-中文网页/TON/TON Telegram 集成突出了区块链社区的协同作用.md"
        - "开始在开放网络上构建": "区块链常识/中文网页/区块链-中文网页/TON/开始在开放网络上构建.md"
        - "TON简介": "区块链常识/中文网页/区块链-中文网页/TON/TON简介.md"
        - "区块链分析": "区块链常识/中文网页/区块链-中文网页/TON/区块链分析.md"
      - "基于EVM":
        - "什么是以太坊虚拟机？": "区块链常识/中文网页/区块链-中文网页/基于EVM/什么是以太坊虚拟机？.md"
        - "以太坊":
          - "以太坊白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/以太坊/以太坊白皮书.md"
          - "以太坊介绍": "区块链常识/中文网页/区块链-中文网页/基于EVM/以太坊/以太坊介绍.md"
          - "以太坊简介": "区块链常识/中文网页/区块链-中文网页/基于EVM/以太坊/以太坊简介.md"
        - "Polygon":
          - "Polygon白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/Polygon/Polygon白皮书.md"
          - "介绍Polygon": "区块链常识/中文网页/区块链-中文网页/基于EVM/Polygon/介绍Polygon.md"
        - "币安智能链":
          - "币安白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/币安智能链/币安白皮书.md"
          - "BNB链概述": "区块链常识/中文网页/区块链-中文网页/基于EVM/币安智能链/BNB链概述.md"
        - "灵知链":
          - "Gnosis白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/灵知链/Gnosis白皮书.md"
          - "Gnosis 概述": "区块链常识/中文网页/区块链-中文网页/基于EVM/灵知链/Gnosis 概述.md"
        - "火币生态链":
          - "火币生态链白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/火币生态链/火币生态链白皮书.md"
          - "HECO链介绍": "区块链常识/中文网页/区块链-中文网页/基于EVM/火币生态链/HECO链介绍.md"
        - "Avalanche":
          - "Avalanche 白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/Avalanche/Avalanche 白皮书.md"
          - "官网": "区块链常识/中文网页/区块链-中文网页/基于EVM/Avalanche/官网.md"
        - "Fantom":
          - "Fantom白皮书": "区块链常识/中文网页/区块链-中文网页/基于EVM/Fantom/Fantom白皮书.md"
          - "Fantom概览": "区块链常识/中文网页/区块链-中文网页/基于EVM/Fantom/Fantom概览.md"
        - "Moonbeam/Moonriver":
          - "关于Moonbream": "区块链常识/中文网页/区块链-中文网页/基于EVM/Moonbeam&Moonriver/关于Moonbream.md"
          - "Moonbeam概览": "区块链常识/中文网页/区块链-中文网页/基于EVM/Moonbeam&Moonriver/Moonbeam概览.md"
      - "L2区块链":
        - "Layer-1 和 Layer-2 区块链扩展解决方案": "区块链常识/中文网页/区块链-中文网页/L2区块链/Layer-1 和 Layer-2 区块链扩展解决方案.md"
        - "Layer- 2 币安学院": "区块链常识/中文网页/区块链-中文网页/L2区块链/Layer- 2 币安学院.md"
        - "Arbitrum":
          - "Arbitrum白皮书": "区块链常识/中文网页/区块链-中文网页/L2区块链/Arbitrum/Arbitrum白皮书.md"
          - "Arbitrum内核": "区块链常识/中文网页/区块链-中文网页/L2区块链/Arbitrum/Arbitrum内核.md"
  - "more":
    - "正文": "区块链常识/more.md"
    - "相关网页中文翻译":
      - "了解区块链技术的完整课程": "区块链常识/中文网页/区块链常识-中文网页/了解区块链技术的完整课程.md"
      - "区块链技术解释": "区块链常识/中文网页/区块链常识-中文网页/区块链技术解释.md"
- "Oracles":
  - "区块链预言机":
    - "正文": "Oracles/区块链预言机.md"
    - "相关网页中文翻译":
      - "什么是区块链预言机？": "Oracles/中文网页/区块链预言机-中文网页/什么是区块链预言机？.md"
  - "混合智能合约":
    - "正文": "Oracles/混合智能合约.md"
    - "相关网页中文翻译":
      - "混合智能合约解释": "Oracles/中文网页/混合智能合约-中文网页/混合智能合约解释.md"
      - "了解混合智能合约的完整指南": "Oracles/中文网页/混合智能合约-中文网页/了解混合智能合约的完整指南.md"
  - "Chainlink":
    - "正文": "Oracles/Chainlink.md"
    - "相关网页中文翻译":
      - "什么是Chainlink？": "Oracles/中文网页/Chianlink-中文网页/什么是Chainlink？.md"
      - "5 分钟了解 Chainlink": "Oracles/中文网页/Chianlink-中文网页/5 分钟了解 Chainlink.md"
  - "Oracles 网络":
    - "正文": "Oracles/Oracles网络.md"
    - "相关网页中文翻译":
      - "分散的 Oracle 网络": "Oracles/中文网页/Oracles网络-中文网页/分散的 Oracle 网络.md"
      - "去中心化 Oracle 网络发展的新手指南": "Oracles/中文网页/Oracles网络-中文网页/分散的 Oracle 网络.md"
      - "了解Oracle 网络": "Oracles/中文网页/Oracles网络-中文网页/了解Oracle 网络.md"
- "智能合约":
  - "智能合约":
    - "正文": "智能合约/智能合约.md"
    - "相关网页中文翻译":
      - "智能合约简介": "智能合约/中文网页/智能合约-中文网页/智能合约简介.md"
      - "什么是智能合约？": "智能合约/中文网页/智能合约-中文网页/什么是智能合约？.md"
      - "智能合约 - 简单解释": "智能合约/中文网页/智能合约-中文网页/智能合约 - 简单解释.md"
  - "ERC代币":
    - "正文": "智能合约/ERC代币.md"
  - "加密钱包":
    - "正文": "智能合约/加密钱包.md"
    - "相关网页中文翻译":
      - "什么是区块链钱包？": "智能合约/中文网页/加密钱包-中文网页/什么是区块链钱包？.md"
      - "什么是加密钱包？ 初学者指南": "智能合约/中文网页/加密钱包-中文网页/什么是加密钱包？ 初学者指南.md"
  - "加密水龙头（Crypto Faucets）":
    - "正文":  "智能合约/加密水龙头（Crypto Faucets）.md"
    - "相关网页中文翻译":
      - "什么是加密水龙头？": "智能合约/中文网页/集成开发环境（IDEs）-中文网页/什么是加密水龙头？.md"
      - "什么是加密水龙头，以及它们是如何工作的?": "智能合约/中文网页/集成开发环境（IDEs）-中文网页/什么是加密水龙头，以及它们是如何工作的？.md"
  - "去中心化存储":
    - "正文": "智能合约/去中心化存储.md"
    - "相关网页中文翻译":
      - "什么是去中心化存储？": "智能合约/中文网页/去中心化存储-中文网页/什么是去中心化存储？.md"
      - "去中心化存储": "智能合约/中文网页/去中心化存储-中文网页/去中心化存储.md"
  - "测试":
    - "正文": "智能合约/测试.md"
    - "相关网页中文翻译":
      - "如何测试以太坊智能合约": "智能合约/中文网页/测试-中文网页/如何测试以太坊智能合约.md"
      - "编写自动化智能合约测试": "智能合约/中文网页/测试-中文网页/编写自动化智能合约测试.md"
      - "在 Solidity 中对以太坊智能合约进行单元测试的技巧": "智能合约/中文网页/测试-中文网页/在 Solidity 中对以太坊智能合约进行单元测试的技巧.md"
      - "Hardhat 中的智能合约代码覆盖率": "智能合约/中文网页/测试-中文网页/Hardhat 中的智能合约代码覆盖率.md"
  - "部署":
    - "正文": "智能合约/部署.md"
    - "相关网页中文翻译":
      - "部署智能合约并与之交互": "智能合约/中文网页/部署-中文网页/部署智能合约并与之交互.md"
  - "监控":
    - "正文": "智能合约/监控.md"
  - "升级":
    - "正文": "智能合约/升级.md"
    - "相关网页中文翻译":
      - "升级智能合约": "智能合约/中文网页/升级-中文网页/升级智能合约.md"
      - "什么是可升级智能合约？ 完整指南": "智能合约/中文网页/升级-中文网页/什么是可升级智能合约？ 完整指南.md"

#  标记：这以下使用的不再是"正文"

- "编程语言":
  - "编程语言-智能合约": "编程语言/编程语言-智能合约.md"
  - "智能合约": 
    - "Solidity": "编程语言/智能合约/Solidity.md"
    - "Vyper": "编程语言/智能合约/Vyper.md"
    - "Rust": "编程语言/智能合约/Rust.md"
  - "编程语言-智能合约周边开发": "编程语言/编程语言-智能合约周边开发.md"
  - "智能合约 周边开发": 
    - "JavaScript": "编程语言/智能合约 周边开发/JavaScript.md"
    - "Go": "编程语言/智能合约 周边开发/Go.md"
    - "Python": "编程语言/智能合约 周边开发/Python.md"
  - "相关网页中文翻译":
    - "如何在 Rust 中编写和部署智能合约": "编程语言/中文网页/如何在 Rust 中编写和部署智能合约-中文网页.md"
    - "在 Y 分钟内学习 Vyper": "编程语言/中文网页/在 Y 分钟内学习 Vyper-中文网页.md"

- "智能合约框架":
  - "智能合约框架": "智能合约框架/智能合约框架.md"
  - "相关网页中文翻译":
    - "以太坊开发者工具的权威列表 - 框架": "智能合约框架/中文网页/以太坊开发者工具的权威列表 - 框架.md"
    - "2022 年您需要的 10 大智能合约开发工具": "智能合约框架/中文网页/2022 年您需要的 10 大智能合约开发工具.md"

- "安全":
  - "安全": "安全/安全.md"
  - "实践": "安全/实践.md"
  - "工具": "安全/工具.md"
  - "相关网页中文翻译":
    - "以太坊智能合约安全建议": "安全/中文网页/以太坊智能合约安全建议.md"
    - "实践":
      - "智能合约模糊测试入门": "安全/中文网页/实践/智能合约模糊测试入门.md"
      - "Solidity智能合约静态代码分析": "安全/中文网页/实践/Solidity智能合约静态代码分析.md"
      - "Solidity Security：已知攻击向量和常见反模式的综合列表": "安全/中文网页/实践/Solidity Security：已知攻击向量和常见反模式的综合列表.md"
      - "区块链攻击向量：最安全技术的漏洞": "安全/中文网页/实践/区块链攻击向量：最安全技术的漏洞.md"
      - "智能合约随机性或复制逻辑攻击": "安全/中文网页/实践/智能合约随机性或复制逻辑攻击.md"

- "管理平台":
  - "管理平台": "管理平台/管理平台.md"

- "版本控制系统":
  - "版本控制系统": "版本控制系统/版本控制系统.md"

- "代码托管服务":
  - "代码托管服务": "代码托管服务/代码托管服务.md"
  - "GitHub": "代码托管服务/Github.md"
  - "GitLab": "代码托管服务/GitLab.md"
  - "Bitbucket": "代码托管服务/Bitbucket.md"
  - "相关中文网页翻译":
    - "如何在专业开发团队中使用 Git": "代码托管服务/中文网页/如何在专业开发团队中使用 Git.md"

- Dapp
  -















theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette:  # 颜色
    primary: 'default'
    accent: 'indigo'
  feature:
    tabs: false  # 横向导航