site_name: Web3-wiki

nav:
- 首页: "index.md"
- "基本区块链知识":
  - "什么是区块链":
    - "正文": "基本区块链知识/什么是区块链.md"
    - "中文网页": 
      - "区块链定义解释": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链定义解释.md"
      - "什么是去中心化？": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是去中心化？.md"
      - "区块链是如何运作的？": "基本区块链知识/中文网页/什么是区块链-中文网页/区块链是如何运作的？.md"
      - "什么是区块链？ | 开发人员的区块链基础知识": "基本区块链知识/中文网页/什么是区块链-中文网页/什么是区块链-开发人员的区块链基础知识.md"
  - "权力下放": 
    - "正文": "基本区块链知识/权力下放.md"
    - "中文网页":
      - "什么是权力下放？": "基本区块链知识/中文网页/权力下放-中文网页/什么是权力下放？.md"
      - "在区块链中，权力下放的作用是什么？": "基本区块链知识/中文网页/权力下放-中文网页/在区块链中，权力下放的作用是什么？.md"
  - "为什么区块链重要":
    - "正文": "基本区块链知识/为什么区块链重要.md"
    - "中文网页":
      - "为什么是区块链？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么是区块链？.md"
      - "什么是区块链，为什么它很重要？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/什么是区块链，为什么它很重要？.md"
      - "Web3/密码:为什么要兼得？": "基本区块链知识/中文网页/为什么区块链重要-中文网页/Web3&密码为什么要兼得？.md"
      - "为什么区块链很重要以及为什么它很重要": "基本区块链知识/中文网页/为什么区块链重要-中文网页/为什么区块链很重要以及为什么它很重要.md"
  - "区块链结构":
    - "正文": "基本区块链知识/区块链结构.md"
    - "中文网页":
      - "区块链架构基础：组件、结构、收益和创造": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构基础：组件、结构、收益和创造.md"
      - "区块链架构 101：组件、结构和优势": "基本区块链知识/中文网页/区块链结构-中文网页/区块链架构 101：组件、结构和优势.md"
      - "区块链结构": "基本区块链知识/中文网页/区块链结构-中文网页/区块链结构.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/区块链结构-中文网页/区块链基础｜Coursera.md"
  - "基本区块链操作":
    - "正文": "基本区块链知识/基本区块链操作.md"
    - "中文网页":
      - "区块链基础知识：结构、操作和比特币区块链": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础知识：结构、操作和比特币区块链.md"
      - "比特币区块链交易 | 比特币开发者": "基本区块链知识/中文网页/基本区块链操作-中文网页/比特币区块链交易--比特币开发者.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/基本区块链操作-中文网页/以太坊区块链交易--ethereum.org.md"
      - "区块链基础｜Coursera": "基本区块链知识/中文网页/基本区块链操作-中文网页/区块链基础--Coursera.md"
  - "区块链技术的应用和用途":
    - "正文": "基本区块链知识/区块链技术的应用和用途.md"
    - "中文网页":
      - "区块链技术的应用和用途": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的应用和用途.md"
      - "区块链技术的十大现实应用": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/区块链技术的十大现实应用.md"
      - "以太坊区块链交易 | ethereum.org": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/以太坊区块链交易--ethereum.org.md"
      - "打破现状的区块链应用和现实世界用例 E34": "基本区块链知识/中文网页/区块链技术的应用和用途-中文网页/打破现状的区块链应用和现实世界用例 E34.md"


theme:
  name: 'material'
  language: 'zh'  # 配置语言
  palette:  # 颜色
    primary: 'default'
    accent: 'indigo'
  feature:
    tabs: false  # 横向导航