name: Automatic Deploy to Github Pages

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  deploy_and_update:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force

